version: "3"
services: 
  dbservice_mysql:
    image: mysql
    environment: 
      # - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - bootcomposeapp

  dbservice_postgre:
    image: postgres
    environment: 
      # - MYSQL_USERNAME=root
      - POSTGRES_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3308:5432
    networks:
      - bootcomposeapp


  user-service:
    build: ./UserService/
    depends_on: 
      - dbservice_mysql
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/user_service?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=test
    ports:
      - 8085:8081
    networks:
      - bootcomposeapp

  product-service:
    build: ./ProductService/
    depends_on: 
      - dbservice_postgre
    environment:
      - spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_app?createDatabaseIfNotExist=true
      - spring.datasource.username=postgres
      - spring.datasource.password=test
    ports:
      - 8086:8082
    networks:
      - bootcomposeapp

networks:
  bootcomposeapp: